CREATE TABLE BOOKS (
    book_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     title VARCHAR(300) NOT NULL, isbn VARCHAR(20) UNIQUE, publication_year INTEGER CHECK (publication_year BETWEEN 1000 AND 2100)
);
CREATE TABLE AUTHORS (
    author_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, full_name VARCHAR(100) NOT NULL
);
CREATE TABLE BOOK_AUTHORS (
    book_id INTEGER NOT NULL REFERENCES books(book_id), 
    author_id INTEGER NOT NULL REFERENCES authors(author_id), PRIMARY KEY (book_id, author_id)
);
CREATE TABLE MEMBERS (
    member_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, full_name VARCHAR(100) NOT NULL, 
    email VARCHAR(255) UNIQUE
);
CREATE TABLE LOANS (
    loan_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    book_id INTEGER NOT NULL REFERENCES books(book_id), 
    member_id INTEGER NOT NULL REFERENCES members(member_id), 
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL, 
    return_date DATE
);
CREATE TABLE FINES (
    fine_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    loan_id INTEGER NOT NULL REFERENCES loans(loan_id), 
    amount NUMERIC(6,2) NOT NULL CHECK (amount >= 0), 
    paid BOOLEAN NOT NULL DEFAULT FALSE
);